### ISSUE TITLE
To-do-list

### ISSUE THREAD

**Issue by Tiffilore** [Tiffilore/Monkey_Business#1]
- [ ] add virgin monkey code
- [ ] add extended-repl
- [ ] add infractructure for commands (:command)
- [ ] implement `:t <statement>` (only shows the type of the object)
- [ ] add ast-extension for latex-trees
- [ ] implement `:<show-tree-command>`
- [ ] implement `:<show-tree-with-eval>`
- [ ] implement `:<show environment-history>`
